version: '3.3'

services:
   dacs2019walter:
     depends_on:
       - dbebooksdiary   
     image: dsi2019ebook:latest
     ports:
       - "8080:8080"
     restart: always
     environment:
       - SPRING_PROFILES_ACTIVE=prod
       - DSI2019_DB_HOST=jdbc:mysql://dbebooksdiary:3306/dbebooksdiary?useTimezone=true&serverTimezone=UTC
       - DSI2019_DB_USERNAME=bob
       - DSI2019_DB_PASSWORD=bob
   dbebooksdiary:
     image: mysql:5.7
     restart: always
#     ports:
#       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: univille
       MYSQL_DATABASE: dbebooksdiary
       MYSQL_USER: bob
       MYSQL_PASSWORD: bob